baseURL = "https://pombadev.github.io"
copyright = "Pomba Magar"
enableEmoji = true
languageCode = "en-us"
theme = "terminal"
title = "Rambling"

[permalinks]
posts = "/:year-:monthname:-:day/:title"

[params]
centerTheme = true
contentTypeName = "posts"
readingTime = true
showLastUpdated = true
themeColor = "red"        # ["orange", "blue", "red", "green", "pink"]

[languages]
[languages.en]
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoHomeLink = "/"
logoText = "Home"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"

[[languages.en.menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/pombadev"

[[languages.en.menu.main]]
identifier = "gitlab"
name = "GitLab"
url = "https://gitlab.com/pombadev"

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags"
